#Tomcat配置
server:
  #端口
  port: 8080
#Spring配置
spring:
  application:
    #应用名称
    name: LayuiModule
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板